// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "testify_test/entity"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *ProductRepository) FindAll() []*entity.Product {
	ret := _m.Called()

	var r0 []*entity.Product
	if rf, ok := ret.Get(0).(func() []*entity.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *ProductRepository) FindById(id string) *entity.Product {
	ret := _m.Called(id)

	var r0 *entity.Product
	if rf, ok := ret.Get(0).(func(string) *entity.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	return r0
}

type mockConstructorTestingTNewProductRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductRepository(t mockConstructorTestingTNewProductRepository) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
